c = input()

c.replace('a', 'z')
c.replace('b', 'y')
c.replace('c', 'x')
c.replace('d', 'w')
c.replace('e', 'v')
c.replace('f', 'u')
c.replace('g', 't')
c.replace('h', 's')
c.replace('i', 'r')
c.replace('j', 'q')
c.replace('k', 'p')
c.replace('l', 'o')
c.replace('m', 'n')
c.replace('n', 'm')
c.replace('o', 'l')
c.replace('p', 'k')
c.replace('q', 'j')
c.replace('r', 'i')
c.replace('s', 'h')
c.replace('t', 'g')
c.replace('u', 'f')
c.replace('v', 'e')
c.replace('w', 'd')
c.replace('x', 'c')
c.replace('y', 'b')
c.replace('z', 'a')

print(c)